### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by guillaumejs2403** [valeoai/STEEX#1]
Hi!

Congrats on your paper. I was wondering when you will release the weights of your models. Additionally, (maybe this is a silly question) when following the celebahq dataset preprocessing it generates 6 folders (x_imgs, x_labels, for x in {train, test, val}). Did you transfer manually to create the layout written in your README.md? Did you merge val and train? I see that you are validating using the test set (`image_val       = "/path/to/dataset/CelebAMask-HQ/test/images"` ). 

Thanks and congrats again!

**Comment by EloiZ** [comment]
Hi Guillaume, thanks for reaching out!
The weights of the model are already released, you should be able to find them here: https://github.com/valeoai/STEEX/releases 
Yes, you can transfer manually to have the same layout written in the README.md
val and train are merged indeed.
Let me know if everything work well,
Best regards,

**Comment by guillaumejs2403** [comment]
Thanks!
