### ISSUE TITLE
BDD Evaluation

### ISSUE THREAD

**Issue by guillaumejs2403** [valeoai/STEEX#2]
Dear All,

I have a small question regarding the subsets where you evaluate your model. In your paper, you said that you evaluate on the validation set of BDD100k (1k total images). Nevertheless, in the code, it seems that you are validating on the BDD-OIA 2.2k validation set.

Could you please answer me on which validation set you test STEEX? (BDD100k (5.3GB partition) validation, BDD100k (10k image subset) validation partition (1k images total images), or the BDD-OIA validation subset (2.2k images)

Thank you.

**Comment by EloiZ** [comment]
Hello Guillaume,
we validate on the 1k images of BDD100k (10k image subset).
What in the code makes you think it is not the case?
Thanks

**Comment by guillaumejs2403** [comment]
Thanks, It was my bad, I confound the dataset_mode and dataset_name flags so I was looking where it shouldn't be. Thanks!

**Comment by EloiZ** [comment]
Ok great!
